export const entitySingularCodes = [
  'iot_data_source',
  'iot_machine',
  'iot_machine_attribute',
  'iot_machine_attribute_bind',
  'iot_machine_field',
  'iot_machine_state',
  'iot_machine_trigger',
  'iot_machine_type',
] as const;
export type TEntitySingularCodes = typeof entitySingularCodes[number];

const entityFieldCodes = {
  'IotDataSource': [
    'id',
    'name',
    'code',
    'description',
    'config',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachine': [
    'id',
    'code',
    'name',
    'description',
    'latestFields',
    'runtimeFields',
    'machineType',
    'state',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachineAttribute': [
    'id',
    'name',
    'code',
    'description',
    'dataType',
    'machines',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachineAttributeBind': [
    'id',
    'machineType',
    'machine',
    'machineAttribute',
    'dataSource',
    'config',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachineField': [
    'id',
    'name',
    'code',
    'description',
    'dataType',
    'machines',
    'clearOnNew',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachineState': [
    'id',
    'name',
    'code',
    'description',
    'color',
    'isUptime',
    'machines',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachineTrigger': [
    'id',
    'name',
    'description',
    'machineType',
    'eventType',
    'eventValue',
    'eventAction',
    'isEnabled',
    'orderNum',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
  'IotMachineType': [
    'id',
    'name',
    'code',
    'description',
    'machines',
    'fields',
    'attributes',
    'states',
    'createdAt',
    'createdBy',
    'updatedAt',
    'updatedBy',
    'deletedAt',
    'deletedBy',
  ],
} as const;
export type TEntityFieldCodes = typeof entityFieldCodes;
export type TEntityCodes = keyof TEntityFieldCodes;
